### ISSUE TITLE
Bug: Invalid Ascii Characters

### ISSUE THREAD

**Issue by NotAddison** [Kandan1/ay23z5szKandan#1]
It seems that some of the ascii characters present in `test.txt` cannot be rendered on MacOS Ventura Version 13.4.1 (c)

<img width="422" alt="image" src="https://github.com/Kandan1/ay23z5szKandan/assets/92768150/f6ffcbf7-30f4-4710-baaa-749c9f71b9a1">

**Comment by Kandan1** [comment]
fuck you nigga

**Comment by NotAddison** [comment]
It appears that the issue has still not been fixed.
